apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  MONGO_URI: "mongodb+srv://hayderguedhami:12345678Haider@cluster0.fxebywo.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  REACT_APP_SERVER_URL: "http://server-service:9000"
  PORT: "9000"
