apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: ticket-management-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  # For Minikube
  type: LoadBalancer
